
name: New Service
description: Create a new service
title: New Service
labels: new-service

body:

    - type: input
      id: service_name
      attributes:
          label: Service Name
          description: The name of the new service
          placeholder: my-new-service
      validations:
          required: true
    - type: input
      id: app_name
      attributes:
          label: App Name
          description: The name of the app associated with the service
          placeholder: my-new-app
      validations:
          required: true
    - type: input
      id: repo_name
      attributes:
          label: Repository Name
          description: The name of the repository for the new service
          placeholder: my-new-repo
      validations:
          required: true
    - type: input
      id: repo_owner
      attributes:
          label: Repository Owner
          description: The owner of the repository
          placeholder: owner-name
      validations:
          required: true

      